services:

  nginx:
    image: registry.hub.docker.com/library/nginx:1.23
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    domainname: "trackerjosecelanocom"
    networks:
      - server_side
    ports:
      - 80:80
      - 443:443
      - 7171:7171
      - 1313:1313
    volumes:
      - nginx-conf:/etc/nginx/conf.d:ro
      - letsencrypt-conf:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot:ro
    depends_on:
      - tracker
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  certbot:
    image: registry.hub.docker.com/certbot/certbot:latest
    volumes:
      - letsencrypt-conf:/etc/letsencrypt:rw
      - certbot-www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  tracker:
    image: registry.hub.docker.com/josecelano/torrust-tracker:docker
    user: ${TORRUST_TRACKER_USER_UID:-1000}:${TORRUST_TRACKER_USER_UID:-1000}
    tty: true
    networks:
      - server_side
    ports:
      - 6969:6969/udp
      - 7070:7070
      - 1212:1212
    volumes:
      - tracker-storage:/app/storage:rw
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  server_side: {}

volumes:
  nginx-conf:
    driver: azure_file
    driver_opts:
      share_name: tracker-josecelano-com-nginx-conf
      storage_account_name: trackerjosecelanocom
  letsencrypt-conf:
    driver: azure_file
    driver_opts:
      share_name: tracker-josecelano-com-letsencrypt-conf
      storage_account_name: trackerjosecelanocom
  certbot-www:
    driver: azure_file
    driver_opts:
      share_name: tracker-josecelano-com-certbot-www
      storage_account_name: trackerjosecelanocom
  tracker-storage:
    driver: azure_file
    driver_opts:
      share_name: tracker-josecelano-com-tracker-storage
      storage_account_name: trackerjosecelanocom
